---
driver:
  name: vagrant
  synced_folders:
    - ['../app', '/minions']
  network:
    - ['forwarded_port', {guest: 4567, host: 4567}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu15
    driver:
      box: bento/ubuntu-15.04


suites:
  - name: minions
